import Foundation

//TODO: -
final class HomeViewModel {
    var planetData: [PlanetData] = [
        PlanetData.init(name: "Mercury", description: "Lorem Ipsum has been the industry's", imageName: "Mercury", planetSceneName: "mercury3d", distance: "1",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "1",
                                                                          discovererImage: "1"))),
        
        PlanetData.init(name: "Venus", description: "Lorem Ipsum has been the industry's", imageName: "Venus", planetSceneName: "venus3d", distance: "2",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "2",
                                                                          discovererImage: "2"))),
        
        PlanetData.init(name: "Earth", description: "Lorem Ipsum has been the industry's", imageName: "Earth", planetSceneName: "earth3d", distance: "3",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "3",
                                                                          discovererImage: "3"))),
        
        PlanetData.init(name: "Mars", description: "Torem Ipsum has been the industry's", imageName: "Mars", planetSceneName: "mars3d", distance: "4",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "4",
                                                                          discovererImage: "4"))),
        
        PlanetData.init(name: "Jupiter", description: "Lorem Ipsum has been the industry's", imageName: "Jupiter", planetSceneName: "jupiter3d", distance: "5",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "5",
                                                                          discovererImage: "5"))),
        
        PlanetData.init(name: "Saturn", description: "Lorem Ipsum has been the industry's", imageName: "Saturn", planetSceneName: "saturn3d", distance: "6",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "6",
                                                                          discovererImage: "6"))),
        
        PlanetData.init(name: "Uranus", description: "Lorem Ipsum has been the industry's", imageName: "Uranus", planetSceneName: "uranus3d", distance: "7",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "7",
                                                                          discovererImage: "7"))),
        
        PlanetData.init(name: "Neptune", description: "Lorem Ipsum has been the industry's", imageName: "Neptune", planetSceneName: "neptune3d", distance: "8",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "",
                                                                          discovererImage: ""))),
        
        PlanetData.init(name: "Pluto", description: "Lorem Ipsum has been the industry's", imageName: "Pluto", planetSceneName: "pluto3d", distance: "9",
                        detailInfo: DetailInfo(adjectives: "",
                                               aphelion: 1,
                                               perihelion: 1,
                                               eccentricity: 11.1,
                                               avgOrbitalSpeed: 11.1,
                                               satellites: "22",
                                               discovererInfo: Discoverer(discovererName: "",
                                                                          discovererImage: ""))),
    ]
    
}
